version: '3.8'

services:
  nose-embedder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nose-embedder-server
    ports:
      - "50051:50051"
    environment:
      - MODEL_PATH=/app/embedder_model.onnx
      - GRPC_PORT=50051
      - GRPC_WORKERS=10
      - GRPC_MAX_MESSAGE_LENGTH=10485760  # 10MB
      - MODEL_INPUT_SIZE=96
      - MODEL_INPUT_CHANNELS=1
    volumes:
      # Optional: Mount model from host for easier updates during development
      # - ./embedder_model.onnx:/app/embedder_model.onnx:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; channel = grpc.insecure_channel('localhost:50051'); channel.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - nose-embedder-network

networks:
  nose-embedder-network:
    driver: bridge
