apiVersion: v1
kind: Secret
metadata:
  name: nose-embedder-secret
  namespace: petdid-network
type: Opaque
stringData:
  # NCP Object Storage 자격증명
  # ⚠️ 주의: 실제 배포 시 이 값들을 실제 자격증명으로 교체하세요
  # 또는 kubectl create secret 명령어로 직접 생성하는 것을 권장합니다
  NCP_ACCESS_KEY: "your-ncp-access-key-here"
  NCP_SECRET_KEY: "your-ncp-secret-key-here"

  # 모델 다운로드용 (선택사항 - NCP에서 모델을 다운로드하는 경우)
  # NCP_MODEL_KEY: "models/embedder_model.onnx"
