apiVersion: v1
kind: Service
metadata:
  name: nose-embedder-service
  namespace: petdid-network
  labels:
    app: nose-embedder
    component: ml-server
spec:
  type: ClusterIP  # 클러스터 내부에서만 접근 가능
  selector:
    app: nose-embedder
  ports:
  - name: grpc
    port: 50052          # 서비스 포트
    targetPort: 50052    # 컨테이너 포트
    protocol: TCP
  sessionAffinity: None  # gRPC는 long-lived connection이므로 불필요

---
# 외부 노출이 필요한 경우 NodePort 사용 (선택사항)
# apiVersion: v1
# kind: Service
# metadata:
#   name: nose-embedder-nodeport
#   namespace: petdid-network
#   labels:
#     app: nose-embedder
# spec:
#   type: NodePort
#   selector:
#     app: nose-embedder
#   ports:
#   - name: grpc
#     port: 50052
#     targetPort: 50052
#     nodePort: 30052  # 30000-32767 범위
#     protocol: TCP
